### ISSUE TITLE
keep ips of last run and only change when different

### ISSUE THREAD

**Issue by osr00** [Hentra/dyndns-netcup-go#1]
For performance reasons it would be good if the application stores the ips it sended last time and first checks only if they are changed. Only when changed it should communicate with the netcup server.

This way it would be possible to start the app once per minute via cron and it only accesses netcup if needed. This would reduces network traffic a lot.

**Comment by Hentra** [comment]
This sounds reasonable. I will try and see if I can implement this behaviour. It requires a cache solution which is currently not build into the system.

**Comment by Hentra** [comment]
Current idea on the implementation of the ip cache: 
- The cache file location must be specified in the configuration as `ip-cache`
- The usage of a cache must be optional
- The time on which the cache is valid should be specified in the configuration `cache-timout` (not sure this is a required feature but its nice to have)

**Comment by osr00** [comment]
To me it does not work correctly.
When changing host+domain to host+"."+domain (3x in cache.go) all is ok.
Thanks for this cute little tool!
