### ISSUE TITLE
not an issue, but a question

### ISSUE THREAD

**Issue by simpixo** [Hentra/dyndns-netcup-go#17]
hi

thanks for the netcup updater. it runs fine  in a lxc container under debian distro. But i have a question. if my public ip change your script will update my ddns subdomain automaticly or do i have to start the app again?

**Comment by Hentra** [comment]
The container will check your public IP depending on the interval that is defined with the environment variable `INTERVAL`. If there are any changes to your public IP it will update the DNS entries accordingly. While the container is running the updates will be done automatically and the container does not need to be restarted.
