### ISSUE TITLE
Automatically Run at 5:00 morning

### ISSUE THREAD

**Issue by ghost** [Hentra/dyndns-netcup-go#9]
Hello i have an issue can someone tell me how to setup my cron that it updates everytime at 5:00 in the morning

sry for opening but im not comfortable with cron -e..

thank you alot

**Comment by Hentra** [comment]
Try to add this `0 5 * * * /path/to/dyndns-netcup-go` to the config file that shows up when you execute `crontab -e`. You need to change the path to the location of the binary.

**Comment by Hentra** [comment]
Closing because response is missing. Feel free to reopen.
